[pytest]
minversion = 8.0
addopts = -v -s --strict-markers
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    get: GET endpoint tests
    post: POST endpoint tests
    put: PUT endpoint tests
    delete: DELETE endpoint tests